name: 'Terraform'
on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Initialize - Phase 1
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check
      
    - name: Terraform Plan - Phase 2
      run: terraform plan
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_PROJECTS_SERVICE_ACCOUNT }}
        TF_VAR_var.gcp_credentials: ${{ secrets.GCP_PROJECTS_SERVICE_ACCOUNT }}
        TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
        TF_VAR_region: ${{ secrets.GCP_REGION }}
        TF_VAR_zone: ${{ secrets.GCP_ZONE }}

    - name: Terraform Apply - Phase 3
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_PROJECTS_SERVICE_ACCOUNT }}
        TF_VAR_var.gcp_credentials: ${{ secrets.GCP_PROJECTS_SERVICE_ACCOUNT }}
        TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
        TF_VAR_region: ${{ secrets.GCP_REGION }}
        TF_VAR_zone: ${{ secrets.GCP_ZONE }}